version: "3"
services:
    dex:
        container_name: Dex
        image: dexidp/dex
        ports:
          - "5556:5556"
        command:
          - dex serve /etc/dex/config.yaml
        volumes:
          - ./dex-config:/etc/dex
    back-end:
        image: node:16
        restart: always
        ports:
            - "3001:3001"
        volumes:
            - ./back-end:/back-end
        working_dir: /back-end
        command: npm run start
    frontend:
        image: node:16
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./front-end:/front-end
        working_dir: /front-end
        command: yarn start
